source 'https://rubygems.org'



  gem 'rspec', '~> 3.1.0'
  gem 'cucumber', '~> 2.1.0'
  gem 'shoulda-matchers', "~> 1.0.0.beta3"
  gem 'capybara', '~> 3.10'
  gem 'selenium-webdriver', '~> 3.142', '>= 3.142.1'
  gem 'allure-cucumber', '~> 0.5.0'
  gem 'pry'
  gem 'launchy'
  gem 'nokogiri'
  gem 'report_builder'
